# example netlify.toml
[build]
  publish = "public"
  command = "gatsby build"
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"
[[redirects]]
  from = "/api/*"
  to = "https://api.thecatapi.com/v1/:splat"
  status = 200
  force = true
  headers = {x-api-key = "2bd8e5f6-5cd5-4478-bada-0c8fd2a8e129"}